AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VulnerableAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref VulnerableUser
      Status: Active  # ⚠️ TRIGGER: ключ активен но не используется