apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
automountServiceAccountToken: false